new Firebase('https://duda-dnd.firebaseio.com').set({employees :[
						{
							id: 0,
							name: 'Yohanan hruschev',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/yoha.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 1,
							name: 'Jonathan Goldfarb',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/jonathan.jpg',
							team: 'core',
							status: 'free',
						},
						{
							id: 2,
							name: 'Eyal Ella',
							image: '',
							team: 'application',
							status: 'busy',
						},
						{
							id: 3,
							name: 'Ronny Shapiro',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/ronnyShapiro.jpg',
							team: 'core',
							status: 'busy',
						},
						{
							id: 4,
							name: 'Liad Yosef',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/liad.jpg',
							team: 'application',
							status: 'free',
						},
						{
							id: 5,
							name: 'Amir Glatt',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/amir.jpg',
							team: '',
							status: 'free',
						},
						{
							id: 6,
							name: 'Amit Knaani',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/amitK.jpg',
							team: 'product',
							status: 'free',
						},
						{
							id: 7,
							name: 'Amit Cohen',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/amitC.jpg',
							team: 'support',
							status: 'free',
						},
						{
							id: 8,
							name: 'Danny Mann',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/danny.jpg',
							team: '',
							status: 'free',
						},
						{
							id: 9,
							name: 'Doron Porat - Erez',
							image: '',
							team: '',
							status: 'free',
						},
						{
							id: 10,
							name: 'Evgeniy Averboukh',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/evg.jpg',
							team: '',
							status: 'free',
						},
						{
							id: 11,
							name: 'Gennady Shumakher',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/gena.jpg',
							team: '',
							status: 'free',
						},
						{
							id: 12,
							name: 'Gilad Foyer',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/gilad.jpg',
							team: '',
							status: 'free',
						},
						{
							id: 13,
							name: 'Maayan Mor',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/maayan.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 14,
							name: 'Nadav Gabay',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/nadav.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 15,
							name: 'Nimrod Golan',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/nimrod.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 16,
							name: 'Ramy Ben Aroya',
							image: '',
							team: '',
							status: 'free',
						},
						{
							id: 17,
							name: 'Roni Landau',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/roniL.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 18,
							name: 'Roni Mizrahi',
							image: '',
							team: '',
							status: 'free',
						},
						{
							id: 19,
							name: 'Rotem Baranes',
							image: '',
							team: '',
							status: 'free',
						},
						{
							id: 20,
							name: 'Shachar Shapira',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/shachar.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 21,
							name: 'Shani Goldberg',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/shaniG.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 22,
							name: 'Shani Mozes',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/shaniM.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 23,
							name: 'Sharon Haver',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/sharon.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 24,
							name: 'Tal Landa',
							image: 'https://s3-eu-west-1.amazonaws.com/duda-dnd/talL.jpeg',
							team: '',
							status: 'free',
						},
						{
							id: 25,
							name: 'Tal Magen',
							image: '',
							team: '',
							status: 'free',
						},
						{
							id: 26,
							name: 'Uri Hoter-Ishay',
							image: '',
							team: '',
							status: 'free',
						}
					]});